// Code generated by Kitex v0.7.3. DO NOT EDIT.

package fileservice

import (
	file "Vnollx/kitex_gen/file"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	UploadFile(ctx context.Context, req *file.UploadFileRequest, callOptions ...callopt.Option) (r *file.UploadFileResponse, err error)
	DeleteFile(ctx context.Context, req *file.DeleteFileRequest, callOptions ...callopt.Option) (r *file.DeleteFileResponse, err error)
	UpdateFileInfo(ctx context.Context, req *file.UpdateFileInfoRequest, callOptions ...callopt.Option) (r *file.UpdateFileInfoResponse, err error)
	GetFileInfo(ctx context.Context, req *file.GetFileInfoRequest, callOptions ...callopt.Option) (r *file.GetFileInfoResponse, err error)
	GetFilesInfo(ctx context.Context, req *file.GetFilesInfoRequest, callOptions ...callopt.Option) (r *file.GetFilesInfoResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kFileServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kFileServiceClient struct {
	*kClient
}

func (p *kFileServiceClient) UploadFile(ctx context.Context, req *file.UploadFileRequest, callOptions ...callopt.Option) (r *file.UploadFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UploadFile(ctx, req)
}

func (p *kFileServiceClient) DeleteFile(ctx context.Context, req *file.DeleteFileRequest, callOptions ...callopt.Option) (r *file.DeleteFileResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteFile(ctx, req)
}

func (p *kFileServiceClient) UpdateFileInfo(ctx context.Context, req *file.UpdateFileInfoRequest, callOptions ...callopt.Option) (r *file.UpdateFileInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.UpdateFileInfo(ctx, req)
}

func (p *kFileServiceClient) GetFileInfo(ctx context.Context, req *file.GetFileInfoRequest, callOptions ...callopt.Option) (r *file.GetFileInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFileInfo(ctx, req)
}

func (p *kFileServiceClient) GetFilesInfo(ctx context.Context, req *file.GetFilesInfoRequest, callOptions ...callopt.Option) (r *file.GetFilesInfoResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetFilesInfo(ctx, req)
}
