// Code generated by Kitex v0.7.3. DO NOT EDIT.

package notificationservice

import (
	notification "Vnollx/kitex_gen/notification"
	"context"
	client "github.com/cloudwego/kitex/client"
	callopt "github.com/cloudwego/kitex/client/callopt"
)

// Client is designed to provide IDL-compatible methods with call-option parameter for kitex framework.
type Client interface {
	GetNotificationsByUserId(ctx context.Context, req *notification.GetNotificationsByUserIdRequest, callOptions ...callopt.Option) (r *notification.GetNotificationsByUserIdResponse, err error)
	DeleteNotification(ctx context.Context, req *notification.DeleteNotificationRequest, callOptions ...callopt.Option) (r *notification.DeleteNotificationResponse, err error)
	SendNotification(ctx context.Context, req *notification.SendNotificationRequest, callOptions ...callopt.Option) (r *notification.SendNotificationResponse, err error)
}

// NewClient creates a client for the service defined in IDL.
func NewClient(destService string, opts ...client.Option) (Client, error) {
	var options []client.Option
	options = append(options, client.WithDestService(destService))

	options = append(options, opts...)

	kc, err := client.NewClient(serviceInfo(), options...)
	if err != nil {
		return nil, err
	}
	return &kNotificationServiceClient{
		kClient: newServiceClient(kc),
	}, nil
}

// MustNewClient creates a client for the service defined in IDL. It panics if any error occurs.
func MustNewClient(destService string, opts ...client.Option) Client {
	kc, err := NewClient(destService, opts...)
	if err != nil {
		panic(err)
	}
	return kc
}

type kNotificationServiceClient struct {
	*kClient
}

func (p *kNotificationServiceClient) GetNotificationsByUserId(ctx context.Context, req *notification.GetNotificationsByUserIdRequest, callOptions ...callopt.Option) (r *notification.GetNotificationsByUserIdResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.GetNotificationsByUserId(ctx, req)
}

func (p *kNotificationServiceClient) DeleteNotification(ctx context.Context, req *notification.DeleteNotificationRequest, callOptions ...callopt.Option) (r *notification.DeleteNotificationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.DeleteNotification(ctx, req)
}

func (p *kNotificationServiceClient) SendNotification(ctx context.Context, req *notification.SendNotificationRequest, callOptions ...callopt.Option) (r *notification.SendNotificationResponse, err error) {
	ctx = client.NewCtxWithCallOptions(ctx, callOptions)
	return p.kClient.SendNotification(ctx, req)
}
