server:
  name: "UserServer"
  host: 127.0.0.1
  #host: 0.0.0.0
  port: 8881

rpc:
  host: 127.0.0.1
  port: 50055

etcd:
  host: 127.0.0.1
  #host: my-etcd
  port: 2379

kafka:
  host: 127.0.0.1
  #host: my-kafka
  port: 9092
